services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /media/WD1T/jelly/config:/config
      - /media/WD1T/jelly/cache:/cache
      - type: bind
        source: /media/WD1T/jelly/media
        target: /media
      - type: bind
        source: /media/WD1T/jelly/media_org
        target: /media_org
        read_only: true
    restart: 'unless-stopped'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]